-- Estrutura do Cofre. SQL portável entre H2 (desenvolvimento e testes) e PostgreSQL (produção).

CREATE TABLE cliente (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(80)  NOT NULL,
    cpf         VARCHAR(11)  NOT NULL,
    email       VARCHAR(120) NOT NULL,
    telefone    VARCHAR(20),
    criado_em   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_cliente_cpf UNIQUE (cpf),
    CONSTRAINT uk_cliente_email UNIQUE (email)
);

CREATE TABLE usuario (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login             VARCHAR(120) NOT NULL,
    nome              VARCHAR(80)  NOT NULL,
    senha_hash        VARCHAR(100) NOT NULL,
    perfil            VARCHAR(10)  NOT NULL,
    cliente_id        BIGINT,
    tentativas_falhas INTEGER      NOT NULL,
    bloqueado_ate     TIMESTAMP(6) WITH TIME ZONE,
    trocar_senha      BOOLEAN      NOT NULL,
    ativo             BOOLEAN      NOT NULL,
    criado_em         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_usuario_login UNIQUE (login),
    CONSTRAINT fk_usuario_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id)
);

CREATE TABLE conta (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_base      INTEGER       NOT NULL,
    numero           VARCHAR(12)   NOT NULL,
    agencia          VARCHAR(4)    NOT NULL,
    cliente_id       BIGINT        NOT NULL,
    saldo            NUMERIC(15,2) NOT NULL,
    limite           NUMERIC(15,2) NOT NULL,
    situacao         VARCHAR(10)   NOT NULL,
    motivo_bloqueio  VARCHAR(200),
    aberta_em        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    encerrada_em     TIMESTAMP(6) WITH TIME ZONE,
    versao           BIGINT        NOT NULL,
    CONSTRAINT uk_conta_numero_base UNIQUE (numero_base),
    CONSTRAINT uk_conta_numero UNIQUE (numero),
    CONSTRAINT fk_conta_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id)
);

CREATE TABLE lancamento (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id           BIGINT        NOT NULL,
    tipo               VARCHAR(30)   NOT NULL,
    valor              NUMERIC(15,2) NOT NULL,
    saldo_apos         NUMERIC(15,2) NOT NULL,
    contraparte        VARCHAR(12),
    contraparte_nome   VARCHAR(80),
    mensagem           VARCHAR(140),
    id_transacao       VARCHAR(40)   NOT NULL,
    chave_idempotencia VARCHAR(64),
    data_hora          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_lancamento_conta FOREIGN KEY (conta_id) REFERENCES conta (id),
    CONSTRAINT uk_lancamento_idempotencia UNIQUE (conta_id, chave_idempotencia)
);
CREATE INDEX ix_lancamento_conta_data ON lancamento (conta_id, data_hora);
CREATE INDEX ix_lancamento_transacao ON lancamento (id_transacao);

CREATE TABLE chave_pix (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id   BIGINT      NOT NULL,
    tipo       VARCHAR(10) NOT NULL,
    valor      VARCHAR(77) NOT NULL,
    criada_em  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_chave_pix_valor UNIQUE (valor),
    CONSTRAINT fk_chave_pix_conta FOREIGN KEY (conta_id) REFERENCES conta (id)
);

CREATE TABLE caixinha (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id   BIGINT        NOT NULL,
    nome       VARCHAR(40)   NOT NULL,
    meta       NUMERIC(15,2),
    saldo      NUMERIC(15,2) NOT NULL,
    criada_em  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    versao     BIGINT        NOT NULL,
    CONSTRAINT fk_caixinha_conta FOREIGN KEY (conta_id) REFERENCES conta (id)
);

CREATE TABLE cartao (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id   BIGINT      NOT NULL,
    numero     VARCHAR(16) NOT NULL,
    validade   VARCHAR(5)  NOT NULL,
    bloqueado  BOOLEAN     NOT NULL,
    criado_em  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_cartao_conta UNIQUE (conta_id),
    CONSTRAINT uk_cartao_numero UNIQUE (numero),
    CONSTRAINT fk_cartao_conta FOREIGN KEY (conta_id) REFERENCES conta (id)
);

CREATE TABLE evento_auditoria (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    usuario    VARCHAR(120) NOT NULL,
    perfil     VARCHAR(10),
    acao       VARCHAR(40)  NOT NULL,
    detalhe    VARCHAR(300),
    origem     VARCHAR(45)
);
CREATE INDEX ix_auditoria_data ON evento_auditoria (data_hora);
