-- Traga seu salário: portabilidade de salário (simulada) e a regra "Pague-se primeiro".
CREATE TABLE portabilidade_salario (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocolo         VARCHAR(20)   NOT NULL,
    conta_id          BIGINT        NOT NULL,
    banco_origem      VARCHAR(3)    NOT NULL,
    empregador        VARCHAR(120)  NOT NULL,
    cnpj_empregador   VARCHAR(14)   NOT NULL,
    salario           NUMERIC(15,2) NOT NULL,
    dia_pagamento     INTEGER       NOT NULL,
    solicitada_em     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    cancelada_em      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_portabilidade_protocolo UNIQUE (protocolo),
    CONSTRAINT fk_portabilidade_conta FOREIGN KEY (conta_id) REFERENCES conta (id)
);
CREATE INDEX ix_portabilidade_conta ON portabilidade_salario (conta_id);

ALTER TABLE conta ADD COLUMN reserva_percentual INTEGER DEFAULT 0 NOT NULL;
